CMR-6731, CMR-6732
nasa/Common-Metadata-Repository pull request #1064
Opened 2020-09-24 19:41 UTC by ygliuvt

Fixed bulk indexing of deleted granules that are also expired.
Fixed bulk indexing of granules/tags to not try to index into all revisions index.

2020-09-24 19:52 UTC, daniel-zamora requested changes
I think we are missing tests for these two scenarios.

2020-09-24 23:50 UTC, ygliuvt commented
I have thought about testing. These are cases that not worth testing: 
1) not indexed deleted granules that are also expired, it takes too much set up to test, not worth it.
2) not index into the non-existent all revisions index for granules and tags, basically need to check there is no exception in logs. there is no good way to test it.
Basically, both cases are not worth setting up via integration testing. We can verify them via manual testing.

2020-09-25 14:15 UTC, daniel-zamora approved these changes

2020-09-25 16:39 UTC, eereiter approved these changes

2020-09-25 16:54 UTC, merged