Cmr 6706 UMM-G 1.6.1 is not preserving ArchiveAndDistributionInformation Name field of UMM-G 1.6 record
nasa/Common-Metadata-Repository pull request #1067
Opened 2020-10-01 17:36 UTC by eereiter

Added archive-distribution-information-name field to the old CMR granule model so that the new UMM-G ArchiveAndDistributionInformation Name element can be translated between UMM-G versions.

2020-10-01 22:44 UTC, daniel-zamora approved these changes

2020-10-02 12:50 UTC, ygliuvt requested changes
ArchiveAndDistributionInformation in UMM-G is an array, i.e. more than one ArchiveAndDistributionInformationType can be present in a granule. This change will not be able to handle it. 

More importantly, this issue happens when retrieving a UMM-G granule in UMM_JSON format, i.e. the granule is converted from one UMM-G version to another. In this case, rather than going through the umm-lib Granule structure then to the latest UMM-G version, CMR should have gone through the UMM-G migration directly instead. If we make the change this way, we don't have to add a new field in umm-lib Granule, the conversion will be faster and the final result will also be lossless.

Recommend to change the transformation strategy to fix this issue.

2020-10-09 13:30 UTC, jceaser commented on system-int-test/test/cmr/system_int_test/ingest/granule_translation_test.clj
> +          (= :echo10 output-format)
what does this line do?

2020-10-09 13:33 UTC, jceaser approved these changes

2020-10-15 16:17 UTC, ygliuvt commented on common-lib/src/cmr/common/util.clj
> +    (nil? x) nil
this line is unnecessary.

2020-10-15 16:17 UTC, ygliuvt commented on common-lib/src/cmr/common/util.clj
> +    (vector? x) (when (not-empty x)
replace `not-empty` with `seq`

2020-10-15 16:33 UTC, ygliuvt approved these changes
Looks good now. Just a couple minor comments.

2020-10-15 17:34 UTC, eereiter commented on common-lib/src/cmr/common/util.clj
> +    (nil? x) nil
removed it

2020-10-15 17:35 UTC, eereiter commented on common-lib/src/cmr/common/util.clj
> +    (vector? x) (when (not-empty x)
replaced it.

2020-10-16 00:59 UTC, merged