CMR-6747 Fixes product ids csv lines in usage metrics
nasa/Common-Metadata-Repository pull request #1074
Opened 2020-10-08 12:33 UTC by daniel-zamora

this PR attempts to address some product ids that weren't being processed in the csv file properly.  Some lines have values that take the form entry-title:version-id, so we split on : and take the entry-title for searching.

2020-10-08 13:20 UTC, jaybarra approved these changes

2020-10-08 13:40 UTC, ygliuvt requested changes
I don't know why you make this code change. The entry listed in CMR-6747 is `CIESIN:410`. There is no collections in PROD that has entry-title of `CIESIN`. So how would this code change fix the entry documented in the issue? 
Note: we don't have to match every entry in the community usage to a collection, if it truly does not make sense, we need to skip the entry and get back to the provider. I feel this entry is this case and the current implementation is doing the right thing.

2020-10-09 14:59 UTC, ygliuvt commented on search-app/src/cmr/search/services/community_usage_metrics/metrics_service.clj
> +            short-name (first (map :short-name (:items results)))]
every item found is guaranteed to have a `short-name`,  so you could just use `(:short-name (first (:items results)))` and put this on line 57.

2020-10-09 15:01 UTC, ygliuvt commented on search-app/src/cmr/search/services/community_usage_metrics/metrics_service.clj
> +                             :all-revisions? true
Why do we care about older revisions? I don't think we should.

2020-10-09 17:47 UTC, ygliuvt approved these changes

2020-10-13 13:12 UTC, merged