Cmr 6814 add tool associations new
nasa/Common-Metadata-Repository pull request #1084
Opened 2020-10-22 22:20 UTC by sxu123

2020-10-23 12:41 UTC, ygliuvt requested changes
This looks really clean. Good job!

We need to: 
1) add test that verifies after a tool association is made, searching the collection in JSON format would show the tool associations. I only see this verification in bulk indexing tools, not in regular tool association.
2) Update API doc mentioning tools as part of collection associations field in JSON response.

2020-10-23 14:35 UTC, jaybarra commented on indexer-app/src/cmr/indexer/data/elasticsearch.clj
> +        (:transaction-id concept)
nitpick, whitespace looks off

2020-10-26 13:26 UTC, ygliuvt commented on search-app/docs/api.md
> +HTTP/1.1 400 BAD REQUEST
I think the status code should be `200` rather than `400`.

2020-10-26 13:27 UTC, ygliuvt commented on search-app/docs/api.md
> +HTTP/1.1 400 BAD REQUEST
Status code should be `200`

2020-10-26 14:51 UTC, ygliuvt approved these changes

2020-10-26 18:44 UTC, jaybarra approved these changes

2020-10-26 18:47 UTC, merged