CMR-6758: Update Elasticsearch version
nasa/Common-Metadata-Repository pull request #1112
Opened 2020-11-17 21:25 UTC by mschmele

2020-11-18 01:05 UTC, daniel-zamora approved these changes

2020-11-18 13:35 UTC, ygliuvt commented
We need to update cloud deployments code to update ES and Kibana version as well and it needs to be tested and deployed first before this can be formally merged.

2020-11-18 21:01 UTC, jaybarra approved these changes

2020-11-18 22:19 UTC, jceaser approved these changes

2020-11-24 15:17 UTC, ygliuvt requested changes
There appears to be spatial related test failures in the build. We need to make sure all tests pass in the build with the ES upgrade. I am surprised 7.10.0 is available in `docker.elastic.co` because the listing is only up to `7.9.3`.

2020-12-17 19:12 UTC, merged