CMR 6849: Change tag association/dissociation partial failure status code to 400
nasa/Common-Metadata-Repository pull request #1138
Opened 2021-01-07 17:04 UTC by yiduoke

2021-01-07 17:55 UTC, mschmele requested changes
Logic looks good - formatting just needs some fixes

2021-01-07 17:55 UTC, mschmele commented on search-app/test/cmr/search/test/api/tags.clj
> +                  (= 200 (:status (tags/tag-api-response dictionary-with-no-error)))))))
You shouldn't need to have this `do` block. Each `is` should run independently. The spacing is also a little off
```suggestion
  (testing "Making sure `tag-api-response` returns status code 400 when there's errors"
      (is (= 400 (:status (tags/tag-api-response dictionary-with-error))))
      (is (= 200 (:status (tags/tag-api-response dictionary-with-no-error)))))))
```

2021-01-07 17:55 UTC, mschmele commented on search-app/test/cmr/search/test/api/tags.clj
> +(def dictionary-with-error [
Nitpick with both `def`s: the object should only be indented 2 spaces. Not a big deal, but it's our convention. Let me know if you can't find an example and I'd be happy to help

2021-01-07 17:55 UTC, mschmele commented on search-app/src/cmr/search/api/tags.clj
> +    (if (has-error? data) (tag-api-response 400 data) (tag-api-response 200 data)))
Fix this formatting like so:
`if <condition>`
`statement to evaluate if true`
`statement to evaluate if false`
```suggestion
    (if (has-error? data) 
      (tag-api-response 400 data)
      (tag-api-response 200 data)))
```

2021-01-07 17:57 UTC, jaybarra requested changes
We should also add a test case in the system-int-test suite.

2021-01-07 17:57 UTC, jaybarra commented on search-app/src/cmr/search/api/tags.clj
> +    (if (has-error? data) (tag-api-response 400 data) (tag-api-response 200 data)))
whitespace nitpick, put the `if` cases on new lines for readability

2021-01-07 17:57 UTC, jaybarra commented on search-app/test/cmr/search/test/api/tags.clj
> +      (do
Unnecessary `do`, the test runner will handle both `is` forms without the extra wrapper. And the `=` can be on the same line as the `is`

2021-01-12 12:45 UTC, jaybarra requested changes
Tests look good but let's just update the error handler function.

2021-01-12 12:45 UTC, jaybarra commented on system-int-test/src/cmr/system_int_test/utils/tag_util.clj
> +       (is (= [400
Let's remove the `if` and duplicate this to make an `assert-tag-association-response-error?` function to handle the 400 case.

2021-01-12 16:48 UTC, jaybarra approved these changes

2021-01-12 16:51 UTC, mschmele approved these changes

2021-01-12 16:54 UTC, merged