CMR-6679 CI build updates
nasa/Common-Metadata-Repository pull request #1139
Opened 2021-01-12 19:44 UTC by jaybarra

Fixes to handle the update build in the CI environment.

2021-01-12 22:07 UTC, mschmele approved these changes

2021-01-12 22:07 UTC, mschmele commented on redis-utils-lib/project.clj
> +            "pull-docker-images" ["shell" "docker" "pull" ~(str "redis:" redis-version)]
This feels a bit overkill, and I think the only reason I didn't feel that way with the elasticsearch version is there wasn't the need for a `str` call. Are the redis and elasticsearch versions being called elsewhere? If not I don't really see the benefit of this, even if it is nifty

2021-01-12 22:07 UTC, mschmele commented on system-int-test/test/cmr/system_int_test/search/collection_concept_retrieval_test.clj
> +        (is (= 200 (:status response)))
👏 

I hate the `_` bindings in `let` blocks

2021-01-13 00:19 UTC, ygliuvt commented on access-control-app/project.clj
> +            "itest" ["kaocha" "--focus" ":integration"]
Add comments on what these targets are for and explain why the ci build is different from local.

2021-01-13 00:23 UTC, ygliuvt commented on bin/functions/test.sh
> +    cmr start uberjar dev-system
Do we need to start dev-system in order to run unit tests?

2021-01-13 00:35 UTC, ygliuvt commented
We should add a high level description on Kaocha and how different groups are set up in ci and basic conventions to follow (e.g. test file must end with `test.clj` etc.) in a README somewhere.

2021-01-13 00:37 UTC, ygliuvt requested changes
Good job! Need some high level documentation on ci setup. It could be in a README or a link in README to a wiki page.

2021-01-13 19:13 UTC, ygliuvt commented on system-int-test/README.md
> +To run the system integration test suite, ensure all required services of CMR are running.
Great documentation.

2021-01-13 19:16 UTC, ygliuvt approved these changes
Bamboo build needs to be modified to produce the necessary artifacts needed by downstream deployment plans (e.g. ES AMI build and ingest-driver, etc.), but that is outside of the scope of this PR.

2021-01-13 19:25 UTC, merged