Bug - CMR-7071 - URL encoded subscription queries fail to run
nasa/Common-Metadata-Repository pull request #1168
Opened 2021-02-06 14:55 UTC by jceaser

It looks like the ingest of subscription was not decoding queries, this was causing the processing code to try to run the raw subscription, which it also encoded before sending over the wire. My approach was to assume "garbage in" and clean on ingest to allow for all downstream users of the data to operate as they have.

Also in this change request are some formatting changes caused by Beautify (blame it not me) and some fixes to tests discovered in the now defunct CMR-6658, such as an unreliable use of forcing a lazy seq was converted to an advance-time in subscription_processing_test.clj, also added a test for the subscription->time-constraint function because its operation is very important to the success of subscriptions query time constraints and having the test makes me feel more confident that the code is working.

2021-02-08 14:36 UTC, mschmele commented on ingest-app/src/cmr/ingest/api/subscriptions.clj
> +      concept-fixed)
You can use `as->` here and remove this let: https://clojuredocs.org/clojure.core/as-%3E

```suggestion
    (as-> metadata metadata
          (codec/form-decode-str (get metadata "Query")
          (assoc metadata "Query" metadata)
          (json/generate-string metadata)
          (assoc concept :metadata metadata-as-str))
```

2021-02-08 14:36 UTC, mschmele commented on ingest-app/test/cmr/ingest/api/subscriptions_test.clj
> +    (get meta-json "Query")))
Nitpick: use thread-last here instead

```suggestion
  (let [meta-json (->> result
                       :metadata
                       json/parse-string]
    (get meta-json "Query")))
```

2021-02-08 14:36 UTC, mschmele commented on system-int-test/test/cmr/system_int_test/ingest/subscription_processing_test.clj
> +    (get meta-json "Query")))
Nitpick: you can thread-first here

```suggestion
  (-> result 
      (get-in [:subscription :metadata])
      json/parse-string]
      (get "Query")))
```

2021-02-08 14:36 UTC, mschmele commented on system-int-test/test/cmr/system_int_test/ingest/subscription_processing_test.clj
> +  (map (fn [x]
Nitpick: can you pick a more descriptive name for this than `x`?

2021-02-08 14:54 UTC, ygliuvt requested changes
Because url decode cannot reliably detect if a string has already been url encoded, we can't just decode any query provided as url encoded without updating our documentation. 

Since the request format is `application/json`, I don't see why we can't just specify that the `Query` field in subscription be url decoded original string form and let EDSC fix their requests. Would requesting the `Query` be url encoded fix the problem or create more problems for us? 

Regardless the solution, we need to update the ingest API doc to specify the `Query` field url encoding. Also we should always save the original request in database, not the modified form -- i.e. we cannot modify the query then save it to db.

2021-02-11 13:23 UTC, jceaser commented
It has been decided by group that this change is not to be added to CMR.

2021-02-11 13:23 UTC, closed without merging