CMR-7216: Implemented has_granules_as_opensearch as alias of has_granules_or_cwic
nasa/Common-Metadata-Repository pull request #1202
Opened 2021-03-19 20:11 UTC by mitchstartzel

* Changed default configured tag for has_granules_or_cwic
* Also added has_granules_or_opensearch as aliased parameter
* Added new tests
* has_granules_or_cwic will be retired in the future

2021-03-19 21:46 UTC, ygliuvt requested changes
Need to update API doc.

2021-03-22 22:12 UTC, mitchstartzel commented
> Need to update API doc.

Bah, left the doc updates in the old branch. Updated!

2021-03-23 13:10 UTC, jaybarra approved these changes

2021-03-23 13:13 UTC, jceaser approved these changes

2021-03-23 13:38 UTC, ygliuvt approved these changes

2021-03-23 17:03 UTC, merged