CMR-7259: Added back stac docs link to CMR Search Landing page.
nasa/Common-Metadata-Repository pull request #1223
Opened 2021-04-14 19:48 UTC by sxu123

2021-04-16 13:44 UTC, jaybarra commented on search-app/src/cmr/search/site/data.clj
> +    :else "https://d3hqnx562z478b.cloudfront.net/docs/index.html"))
Do we have any way to convert this to a nicer looking path?

2021-04-16 14:54 UTC, jaybarra approved these changes
Having it be available is a start, but it appears to be missing functionality in the side panel.

2021-04-22 12:52 UTC, ygliuvt commented on search-app/resources/templates/stac-search-docs.html
> +   CMR STAC Links contain three parts:
nit: I don't think this sentence is necessary.

2021-04-22 12:52 UTC, ygliuvt commented on search-app/resources/templates/stac-search-docs.html
> +  <li><a href="{{ stac-docs-url }}">CMR STAC Documentation</a> - CMR STAC Catalog Documentation</li>
nit: I would put the documentation link as the first link.

2021-04-22 12:55 UTC, ygliuvt commented on search-app/src/cmr/search/site/data.clj
> +    (string/includes? stac-base-url "sit") "https://d3se4zjsrvasc2.cloudfront.net/docs/index.html"
I don't think this is allowed.

2021-04-22 12:56 UTC, ygliuvt requested changes
Make internal urls config parameters.

2021-04-28 13:35 UTC, ygliuvt approved these changes

2021-04-28 13:50 UTC, merged