CMR-7808: increase DB variable Name column to 256 to match UMM-Var schema length
nasa/Common-Metadata-Repository pull request #1380
Opened 2021-11-05 15:18 UTC by charleshuang80

2021-11-05 15:19 UTC, charleshuang80 commented
work in progress, not sure what DB specific tests to include.

2021-11-08 14:57 UTC, ygliuvt commented on metadata-db-app/src/cmr/metadata_db/migrations/076_increase_variable_name_length.clj
> +  (h/sql "update METADATA_DB.cmr_variables set variable_name = substr(variable_name,1,256)")
This should be `80`, not `256`.

2021-11-08 14:58 UTC, ygliuvt requested changes
Need to update down migration.

2021-11-08 22:21 UTC, ygliuvt approved these changes

2021-11-09 13:14 UTC, jaybarra approved these changes

2021-11-09 15:19 UTC, merged