CMR-8009 - Updating static KMS file for platforms to provide SIT with test data
nasa/Common-Metadata-Repository pull request #1420
Opened 2022-01-19 22:31 UTC by jceaser

SIT needs test data, updating the CSV file inside of CMR to be used on SIT as defined by the /sit/indexer/CMR_KMS_SCHEME_OVERRIDE_JSON parameter in AWS. Only SIT will use this file because CMR in SIT can not communicate to KMS in SIT or even UAT.

This file has the correct number of columns, correct line ending, and the most up-to-date platform data.

Also updating a comment in code to show how to validate the file.

2022-01-19 22:40 UTC, sritz-23 approved these changes

2022-01-20 03:37 UTC, sxu123 approved these changes

2022-01-20 12:36 UTC, eereiter approved these changes

2022-01-20 13:15 UTC, jaybarra requested changes

2022-01-20 13:15 UTC, jaybarra commented on transmit-lib/src/cmr/transmit/kms.clj
> +  (clojure.pprint/pprint (get-keywords-from-system :platforms))
Please remove the pprint

2022-01-20 13:18 UTC, jaybarra approved these changes

2022-01-20 13:33 UTC, merged