CMR-8046 - a bug fix to isolate parse errors which can happen if CSV …
nasa/Common-Metadata-Repository pull request #1449
Opened 2022-02-04 22:05 UTC by jceaser

Background: If KMS changes it's structure and CMR team does not get notified, CMR will fail to parse the new CSV file. When this happens, CMR use to throw an exception from inside a for loop where CMR integrates over schema names (platforms, instruments, science keywords) to download CSV files to process. When this happens nothing catches the exception and the for loop stops processing schemes meaning all schemes with valid data which happens latter in the loop do not get processed.

Fix: Don't throw exception. Instead, return true/false in a tester function and handle that state latter on.

2022-02-04 23:19 UTC, ygliuvt commented on transmit-lib/src/cmr/transmit/kms.clj
>  (defn- validate-subfield-names
change the function name to something like `subfield-names-valid?`

2022-02-04 23:20 UTC, ygliuvt approved these changes

2022-02-05 10:59 UTC, eereiter approved these changes

2022-02-06 23:01 UTC, jaybarra requested changes

2022-02-06 23:01 UTC, jaybarra commented on transmit-lib/test/cmr/transmit/test/kms.clj
> +    (is nil? (#'cmr.transmit.kms/parse-entries-from-csv :platforms sample-csv))))
```suggestion
  (testing "Invalid subfield names in the CSV returns nothing"
    (is (nil? (#'cmr.transmit.kms/parse-entries-from-csv :platforms sample-csv)))))
```
```

2022-02-06 23:03 UTC, jaybarra commented on transmit-lib/test/cmr/transmit/test/kms.clj
> +      (is (= nil result)))))
```suggestion
      (is (nil? result)))))
```

2022-02-06 23:03 UTC, jaybarra commented on transmit-lib/test/cmr/transmit/test/kms.clj
> +
Whitespace, extra newline

2022-02-06 23:05 UTC, jaybarra commented on transmit-lib/test/cmr/transmit/test/kms.clj
> +
```suggestion
```

2022-02-07 14:23 UTC, jceaser commented on transmit-lib/test/cmr/transmit/test/kms.clj
> +      (is (= nil result)))))
I rewrote this section to use are3

2022-02-07 14:24 UTC, jceaser commented on transmit-lib/test/cmr/transmit/test/kms.clj
> +    (is nil? (#'cmr.transmit.kms/parse-entries-from-csv :platforms sample-csv))))
thanks

2022-02-07 17:51 UTC, jaybarra approved these changes

2022-02-07 17:59 UTC, merged