Cmr 3935
nasa/Common-Metadata-Repository pull request #1507
Opened 2022-03-25 15:28 UTC by zimzoom

2022-03-25 20:36 UTC, eereiter requested changes

2022-03-25 20:36 UTC, eereiter commented on umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/dif10.clj
> +                (if (date/metadata-review-date c)
This should be (if (date/metadata-delete-date c)

2022-03-28 11:57 UTC, jaybarra approved these changes

2022-03-28 11:57 UTC, jaybarra commented on tea-config-generator/serverless.yml
> +    description: Return a summery of the calls that can be made to this application
```suggestion
    description: Return a summary of the calls that can be made to this application
```

2022-03-28 13:44 UTC, eereiter approved these changes

2022-03-28 14:13 UTC, jceaser commented on tea-config-generator/serverless.yml
> +    description: Return a summery of the calls that can be made to this application
I caused this.

2022-03-28 14:19 UTC, jceaser approved these changes
I would like to know what is up with the merge and why the tea stuff showed up here, but other then that I see nothing wrong.

2022-03-28 22:33 UTC, merged