CMR-8119 Adds POST/parameter search for stac format
nasa/Common-Metadata-Repository pull request #1517
Opened 2022-03-31 13:23 UTC by daniel-zamora

This PR allows for search-app concept search endpoint returning a stac format to use POST requests with parameters that are equivalent to GET requests with the same parameters.  This does not include JSON queries.

2022-04-01 11:59 UTC, jaybarra approved these changes
Just need to remove the proto-repl reference

2022-04-01 11:59 UTC, jaybarra commented on search-app/src/cmr/search/results_handlers/stac_results_handler.clj
> +    (proto-repl.saved-values/save 6)
```suggestion
```

2022-04-01 13:40 UTC, eereiter approved these changes

2022-04-01 19:00 UTC, ygliuvt commented on search-app/src/cmr/search/api/concepts_search.clj
> +      (find-concepts (merge ctx {:method "GET"}) path-w-extension params headers query-string))
CMR standard is to use keyword `:get` rather than string `"GET"`

2022-04-01 19:04 UTC, ygliuvt commented on system-int-test/src/cmr/system_int_test/data2/stac.clj
> +                   :href (href)}))
Where is the `page_num` in POST? I don't think this works.

2022-04-01 19:04 UTC, ygliuvt commented on system-int-test/src/cmr/system_int_test/data2/stac.clj
> +                   :href (href)}))
Also what if there is combination of query string in the POT body and parameters?

2022-04-01 19:05 UTC, ygliuvt requested changes
The `page_num` is not handled correctly in POST links. There is also a question of combination of query string and query params.

2022-04-11 18:30 UTC, ygliuvt commented
We should update the API doc for STAC POST.

2022-04-11 19:20 UTC, ygliuvt approved these changes

2022-04-11 21:38 UTC, merged