CMR-8171: Add subscription type filtered to subscription search endpoint
nasa/Common-Metadata-Repository pull request #1551
Opened 2022-05-03 16:15 UTC by brianalexander

This PR will make it possible to filter subscriptions based on their type [granule or collection] by adding a new param to the already existing subscription search endpoint.

Changes
1. Add subscription type to elasticsearch mapping
2. Add 'type' to [subscription search endpoint](https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#searching-for-subscriptions) params
3. Add test for type param

2022-05-03 16:37 UTC, ygliuvt commented on system-int-test/test/cmr/system_int_test/search/subscription/subscription_search_test.clj
> +                                                                     :CollectionConceptId (:concept-id coll1)
Remove this line. Collection subscription should not have `CollectionConceptId` field.

2022-05-03 16:38 UTC, ygliuvt commented on system-int-test/test/cmr/system_int_test/search/subscription/subscription_search_test.clj
> +                                                                     :CollectionConceptId (:concept-id coll2)
Remove this line. Collection subscription should not have `CollectionConceptId` field.

2022-05-03 16:40 UTC, ygliuvt commented on system-int-test/test/cmr/system_int_test/search/subscription/subscription_search_test.clj
> +      {:type "collection" :provider "*2" "options[provider][pattern]" true})))
nit: no need to search provider via pattern, just change this line to: `{:type "collection" :provider "PROV2"}`

2022-05-03 16:44 UTC, ygliuvt requested changes
Need to update API doc to include the new subscription search parameter.

2022-05-03 16:56 UTC, isja17 approved these changes

2022-05-04 12:45 UTC, jaybarra commented on indexer-app/src/cmr/indexer/data/concepts/subscription.clj
> +      (assoc doc-for-deleted :metadata-format (name (mt/format-key format))))))
Should make sure we end with a newline per the style-guide. You should be able to check your editor settings for automatically making one.

2022-05-04 12:50 UTC, jaybarra requested changes

2022-05-04 12:50 UTC, jaybarra commented on system-int-test/src/cmr/system_int_test/data2/umm_spec_subscription.clj
> +         subscription (if (and (contains? attribs :Type) (= (:Type attribs) "collection"))
This can be simplified, `(if (= "collection" (:Type attribs))`, the `and` shouldn't be needed.

2022-05-04 14:44 UTC, ygliuvt commented on indexer-app/src/cmr/indexer/data/concepts/subscription.clj
> +          :subscription-name-lowercase (util/safe-lowercase subscription-name)
Name is a required field in subscription, we don't need `safe-lowercase` here.

2022-05-04 14:44 UTC, ygliuvt commented on indexer-app/src/cmr/indexer/data/concepts/subscription.clj
> +          :subscriber-id-lowercase (util/safe-lowercase subscriber-id)
subscriber-id cannot be nil, we don't need `safe-lowercase` here.

2022-05-04 14:56 UTC, ygliuvt commented on system-int-test/src/cmr/system_int_test/data2/umm_spec_subscription.clj
> +   (let [sample-subscription (merge (sample-umm-subscription version) attribs)
I made a similar change in my PR and it is merged now. You can remove this change and just pull in my changes.

2022-05-04 15:00 UTC, ygliuvt approved these changes

2022-05-04 15:24 UTC, merged