CMR-8040 Updated the hard-coded support email to use defconfig
nasa/Common-Metadata-Repository pull request #1607
Opened 2022-07-14 20:37 UTC by eriknelson11

2022-07-15 15:19 UTC, ygliuvt requested changes
Since this support email is already configured in ingest app in `cmr.ingest.config`. We should consolidate this `cmr-support-email` configuration and put it in `cmr.common-app.config` so that both ingest app and search app can use it.

2022-07-15 20:03 UTC, zimzoom approved these changes

2022-07-15 20:27 UTC, ygliuvt commented on ingest-app/src/cmr/ingest/services/granule_bulk_update_service.clj
> +   [cmr.common-app.config :as common-app-config]
nit: We sort required namespaces in alphabetic order. Move this line up. This comment applies to other files too.

2022-07-15 20:29 UTC, ygliuvt commented on system-int-test/test/cmr/system_int_test/search/all_granule_search_test.clj
> +        err-msg (str "The CMR does not allow querying across granules in all collections. To help optimize your search, you should limit your query using conditions that identify one or more collecti
nit: I actually prefer the expected error message in tests be hardcoded string.

2022-07-15 20:32 UTC, ygliuvt approved these changes
Approved with some minor comments.

2022-07-18 18:01 UTC, jceaser commented on system-int-test/test/cmr/system_int_test/search/granule_search_test.clj
> +        [] "NON_EXISTENT" {}
Erick can not access that page, but we created ESD-4083 to add him to the needed groups.

2022-07-18 18:18 UTC, jceaser requested changes
some simple changes needed

2022-07-18 18:18 UTC, jceaser commented on search-app/src/cmr/search/results_handlers/opendata_results_handler.clj
> +   [cmr.common.util :as util]
trailing space

2022-07-18 18:18 UTC, jceaser commented on search-app/src/cmr/search/results_handlers/opendata_results_handler.clj
> +(def DEFAULT_CONTACT_EMAIL
trailing space

2022-07-18 18:18 UTC, jceaser commented on system-int-test/test/cmr/system_int_test/search/granule_search_test.clj
> +            :errors [(str "Excessive query rate. Please contact support@earthdata.nasa.gov.")]}
is this needed, the str?

2022-07-19 15:53 UTC, merged