CMR-8578: Removing 'bearer' prefix string; removing extra debug conso…
nasa/Common-Metadata-Repository pull request #1665
Opened 2022-08-23 16:42 UTC by eudoroolivares2016

When indexing collections using the bootstrap function, the system token was not being parsed due to the bearer prefix. This removes the prefix; further actions will need to be taken under this PR to allow for all collections to be indexed as opposed to only public collections

2022-08-23 19:15 UTC, eereiter approved these changes

2022-08-23 19:26 UTC, jaybarra approved these changes

2022-08-23 19:44 UTC, ygliuvt requested changes
`CMR_TOKEN_KEY` environment variable should be set up in the serverless.yml file

2022-08-24 17:51 UTC, ygliuvt approved these changes

2022-08-25 21:01 UTC, eudoroolivares2016 commented
Currently holding off merging this; linked NGAP ticket has to be completed so that graphql can retrieve data from Neptune, so that we can remove the public endpoint, so that we can index private records

2022-08-30 13:31 UTC, jceaser approved these changes

2022-09-07 16:07 UTC, merged