CMR-9694: Updates the README
nasa/Common-Metadata-Repository pull request #2064
Opened 2024-02-21 20:57 UTC by abbottry

Following the README to setup CMR was confusing, I went through the process and made any relevant updates as well as removed unnecessary steps that were causing confusion.

2024-02-21 20:59 UTC, Bccorb approved these changes

2024-02-21 21:00 UTC, macrouch approved these changes

2024-02-22 14:01 UTC, zimzoom approved these changes

2024-03-01 19:28 UTC, jceaser commented on README.md
> +   {:dev-config {:env {:cmr-metadata-db-password "CHANGE_ME"
did you mean to make this change?

2024-03-01 19:30 UTC, jceaser commented on README.md
> +VS Code has an extension that allows for easier develop of clojure applications.
please consider putting satirical emoji quotes around the word easier

2024-03-01 19:32 UTC, jceaser commented on README.md
> -## License
should we not continue to leave this at the bottom like everything else on the web?

2024-03-01 19:33 UTC, jceaser requested changes
I think at the very least, bump up the year to 2024

2024-03-07 16:28 UTC, jceaser commented on README.md
> +# License
should be an h2, only one h1 should be in the document. Also, this is the second License section

2024-03-07 16:33 UTC, jceaser approved these changes

2024-03-07 17:10 UTC, merged