CMR-9914: CMR Granule Search With V2 Facets Returns Inapplicable Error Message for Deleted Collection
nasa/Common-Metadata-Repository pull request #2127
Opened 2024-06-03 12:21 UTC by TylerHeald1

# Overview

### What is the feature/fix?

Removed a check for no collection being searched in validator so that a query can return 0 hits

### What is the Solution?

Removed a check for no collection being searched in validator so that a query can return 0 hits

### What areas of the application does this impact?

Search

# Checklist

- [x] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [x] New and existing unit and int tests pass locally and remotely with my changes
- [ ] I have removed unnecessary/dead code and imports in files I have changed
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have cleaned up integration tests by doing one or more of the following:
  - de-duped, consolidated, removed dead int tests
  - transformed applicable int tests into unit tests
  - refactored to reduce number of system state resets by updating fixtures (use-fixtures :each (ingest/reset-fixture {})) to be :once instead of :each

2024-06-03 16:20 UTC, isja17 approved these changes

2024-06-04 14:03 UTC, eereiter commented on system-int-test/test/cmr/system_int_test/search/facets/granule_v2_facets_search_test.clj
> +           _ (error "Printing the response " response)]
need to get rid of debugging code.

2024-06-04 14:05 UTC, eereiter requested changes
just remove debugging statement.

2024-06-04 14:32 UTC, eereiter approved these changes

2024-06-04 15:08 UTC, merged