CMR-10139: Re-writing the cache contents to cover when the same subscription is updated.
nasa/Common-Metadata-Repository pull request #2183
Opened 2024-10-22 19:56 UTC by eereiter

# Overview

### What is the feature/fix?

When a subscription is created or deleted update the subscription cache so that granule ingest subscriptions can be filtered out quickly.

### What is the Solution?

Changed Metadata_db concept_service and subscriptions to call to cache or remove subscription information needed to get granule CRUD events for notifications.

### What areas of the application does this impact?

Metadata_db concept_service and subscriptions

# Checklist

- [Z] I have updated/added unit and int tests that prove my fix is effective or that my feature works
- [X] New and existing unit and int tests pass locally and remotely
- [X] clj-kondo has been run locally and all errors corrected
- [X] I have removed unnecessary/dead code and imports in files I have changed
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have cleaned up integration tests by doing one or more of the following:
  - migrated any are2 tests to are3 in files I have changed
  - de-duped, consolidated, removed dead int tests
  - transformed applicable int tests into unit tests
  - refactored to reduce number of system state resets by updating fixtures (use-fixtures :each (ingest/reset-fixture {})) to be :once instead of :each

2024-10-22 20:16 UTC, jmaeng72 approved these changes

2024-10-23 13:21 UTC, TylerHeald1 commented on metadata-db-app/test/cmr/metadata_db/test/services/subscriptions_test.clj
> +       "Adding new subscription with existing modes."
How about making the new-modes for this one just ["Delete"] so that not all the test cases are expected==new-modes

2024-10-23 13:25 UTC, TylerHeald1 requested changes
The one test I left a comment on should have a test case such that expected =/= new-modes

2024-10-23 13:56 UTC, TylerHeald1 commented on metadata-db-app/test/cmr/metadata_db/test/services/subscriptions_test.clj
> +       "Adding new subscription with existing modes."
I'm confused, this still seems to be expected outcome == new modes. I meant something like
expected ["Delete" "New"]
existing ["New"]
new ["Delete"]

2024-10-23 14:08 UTC, merged